project:
  type: website

website:
  title: Dim Red
  search: false
  navbar:
    pinned: false
    collapse: false
    left:
      - text: "home"
        href: index.qmd
  page-footer:
    background: light # or `dark`
    left: Copyleft 2025, Nishant Aswani

format:
  html:
    theme: 
      - default
      - styles/_variables.scss
      - styles/_navbar.scss
    toc: true    
    anchor-sections: false
    self-contained: true
    date-format: long




