project:
  type: website

website:
  title: "DimRed"
  navbar:
    logo-href: index.qmd
    pinned: true
    search: false
    collapse: true
    collapse-below: md
    toggle-position: right
    right:
      - href: blog.qmd
        text: Blog
      - text: Contribute
        menu:
        - text: Source Code
          href:  https://nishantaswani.com
        - text: Report a Bug
          href:  https://nishantaswani.com

format:
  html:
    theme:
      - cosmo
      - styles/styles.scss
